### PR TITLE
add subagency for DAP

### PR DESCRIPTION
**Pull request by ryanwoldatwork**
this is dependent on https://github.com/18F/uswds-jekyll/issues/204, and upgrading this project's Gemfile to include the updated `uswds-jekyll` .gem after it supports the `subagency` parameter.

### CODE REVIEW

**Comment by ryanwoldatwork** [comment]
cc @ryanhofdotgov, @gbinal for review

**Review by ryanhofdotgov — APPROVED** [review]
LGTM! The template I was going to apply will solve this as well, but this gets it done by today's digital council deadline. Thanks!

**Comment by ryanhofdotgov** [comment]
Unfortunately, the upgrade to uswds-jekyll seems to have adversely changed the layout of the site. 

Before:
Screen Shot 2020-10-01 at 11 11 12 AM

After:
Screen Shot 2020-10-01 at 11 09 40 AM

This guide isn't set up properly with Federalist previews in the PRs, so just took a chance when I merged. I'm going to revert this PR in #116, and then do a proper fix tomorrow or early next week.

**Comment by ryanwoldatwork** [comment]
I think it bumped from USWDS 1 to 2. Thus, layout breakage.

**Pull request merged**
