### PR TITLE
Correcting the broken header image link.

### PR DESCRIPTION
**Pull request by DavidEBest**

### CODE REVIEW

**Comment by DavidEBest** [comment]
Corrects #13.

The logourl needs to start with a slash, like https://github.com/18F/guides-template/blob/18f-pages/_config.yml#L25

**Comment by wslack** [comment]
Just noticed the same thing, LGTM :+1:

**Comment by wslack** [comment]
@ultrasaurus flagging for you

**Comment by ultrasaurus** [comment]
weird, used to work :/

**Pull request merged**
