### PR TITLE
Add guides_style_18f and back-link

### PR DESCRIPTION
**Pull request by bplmp**
Noticed the Agile guide wasn't using the guides_style so I added it. Some of the sidebar functionality is still off: when clicking the links some of them don't stay active (they don't display the little blue line to the left of the link in the sidebar).

### CODE REVIEW

**Comment by mbland** [comment]
This is cool! But could you `bundle update --source guides_style_18f` to get the latest version? (Maybe the same for `jekyll`, too, since 3.0.1 is out now.)

**Comment by mbland** [comment]
Oh, and can you post a screenshot demonstrating the guide is rendering properly?

**Comment by bplmp** [comment]
I've updated the Gemfile.lock to include newer versions of guides_style_18f, jekyll, and listen.
I've also been using Cloud9 to do this, so unless it hibernates the server, it should be up and running at: https://agile-18f-bernardol.c9users.io/

Here are a couple screenshots:
image

image

**Comment by ultrasaurus** [comment]
@bplmp thanks for this contribution.  I'm all for it in principle.  Sadly we had gotten behind in accepting PRs, so now there's a merge conflict.  

Anyone have time to rebase and merge?

**Comment by mbland** [comment]
Working on this now... Gonna take a little extra tweaking, but won't take long. Think I'll have to submit a PR to @bplmp's fork/branch, then once that's merged, we can merge this PR.

**Comment by mbland** [comment]
Wow, OK, this is a little tricky... Normally since all 18F folks have push access to 18F repos, we can just push commits directly to a team member's branch, etc. But I'm hitting a little snag here.

@bplmp I've created a new branch on this repo, `guides-style-resolve-conflicts`. It's your branch rebased onto the current `18F/agile#18f-pages`, with conflicts resolved and another commit to resolve a couple other small issues. You to you if you want to try to pull that branch and reset your branch for this PR, or if you're OK with me opening a new PR directly. Your commits will still appear in the history.

**Comment by bplmp** [comment]
@mbland , I'm fine with you opening a new PR directly, if that's simpler to do!

**Pull request closed without merging**
